<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Bangka","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Bangka Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Bangka Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Bangka Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Belitung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kabupaten Belitung Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 1,"name" => "Kota Pangkalpinang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Lampung Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Lampung Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Lampung Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Lampung Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Lampung Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Mesuji","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Pesawaran","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Pesisir Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Pringsewu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Tanggamus","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Tulang Bawang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Tulang Bawang Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kabupaten Way Kanan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kota Bandar Lampung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 2,"name" => "Kota Metro","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kabupaten Lebak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kabupaten Pandeglang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kabupaten Serang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kabupaten Tangerang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kota Cilegon","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kota Serang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kota Tangerang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 3,"name" => "Kota Tangerang Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Bandung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Bandung Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Bekasi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Bogor","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Ciamis","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Cianjur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Cirebon","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Garut","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Indramayu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Karawang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Kuningan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Majalengka","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Pangandaran","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Purwakarta","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Subang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Sukabumi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Sumedang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kabupaten Tasikmalaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Bandung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Banjar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Bekasi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Bogor","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Cimahi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Cirebon","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Depok","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Sukabumi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 4,"name" => "Kota Tasikmalaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kabupaten Administrasi Kepulauan Seribu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kota Administrasi Jakarta Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kota Administrasi Jakarta Pusat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kota Administrasi Jakarta Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kota Administrasi Jakarta Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 5,"name" => "Kota Administrasi Jakarta Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Banjarnegara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Banyumas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Batang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Blora","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Boyolali","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Brebes","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Cilacap","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Demak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Grobogan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Jepara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Karanganyar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Kebumen","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Kendal","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Klaten","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Kudus","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Magelang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Pati","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Pekalongan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Pemalang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Purbalingga","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Purworejo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Rembang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Semarang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Sragen","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Sukoharjo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Tegal","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Temanggung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Wonogiri","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kabupaten Wonosobo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Magelang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Pekalongan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Salatiga","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Semarang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Surakarta","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 6,"name" => "Kota Tegal","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 7,"name" => "Kabupaten Bantul","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 7,"name" => "Kabupaten Gunungkidul","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 7,"name" => "Kabupaten Kulon Progo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 7,"name" => "Kabupaten Sleman","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 7,"name" => "Kota Yogyakarta","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Bangkalan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Banyuwangi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Blitar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Bojonegoro","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Bondowoso","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Gresik","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Jember","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Jombang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kediri","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Lamongan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Lumajang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Madiun","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Magetan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Malang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Mojokerto","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Nganjuk","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Ngawi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Pacitan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Pamekasan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Pasuruan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Ponorogo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Probolinggo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Sampang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Sidoarjo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Situbondo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Sumenep","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Trenggalek","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Tuban","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Tulungagung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Batu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Blitar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Kediri","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Madiun","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Malang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Mojokerto","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Pasuruan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Probolinggo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 8,"name" => "Kota Surabaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Badung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Bangli","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Buleleng","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Gianyar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Jembrana","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Karangasem","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Klungkung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kabupaten Tabanan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 9,"name" => "Kota Denpasar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Bima","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Dompu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Lombok Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Lombok Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Lombok Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Lombok Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Sumbawa","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kabupaten Sumbawa Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kota Bima","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 10,"name" => "Kota Mataram","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Barat Daya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Besar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Jaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Singkil","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Tamiang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Tenggara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Aceh Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Bener Meriah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Bireuen","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Gayo Lues","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Nagan Raya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Pidie","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Pidie Jaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kabupaten Simeulue","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kota Banda Aceh","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kota Langsa","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kota Lhokseumawe","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kota Sabang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 11,"name" => "Kota Subulussalam","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Alor","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Belu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Ende","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Flores Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Kupang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Lembata","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Malaka","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Manggarai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Manggarai Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Manggarai Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Nagekeo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Ngada","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Rote Ndao","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sabu Raijua","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sikka","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sumba Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sumba Barat Daya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sumba Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Sumba Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Timor Tengah Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kabupaten Timor Tengah Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 12,"name" => "Kota Kupang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Bengkayang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Kapuas Hulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Kayong Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Ketapang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Kubu Raya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Landak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Melawi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Mempawah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Sambas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Sanggau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Sekadau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kabupaten Sintang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kota Pontianak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 13,"name" => "Kota Singkawang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Balangan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Banjar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Barito Kuala","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Hulu Sungai Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Hulu Sungai Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Hulu Sungai Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Kotabaru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Tabalong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Tanah Bumbu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Tanah Laut","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kabupaten Tapin","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kota Banjarbaru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 14,"name" => "Kota Banjarmasin","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Barito Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Barito Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Barito Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Gunung Mas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Kapuas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Katingan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Kotawaringin Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Kotawaringin Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Lamandau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Murung Raya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Pulang Pisau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Sukamara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kabupaten Seruyan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 15,"name" => "Kota Palangka Raya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Berau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Kutai Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Kutai Kartanegara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Kutai Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Mahakam Ulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Paser","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kabupaten Penajam Paser Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kota Balikpapan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kota Bontang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 16,"name" => "Kota Samarinda","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 17,"name" => "Kabupaten Bulungan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 17,"name" => "Kabupaten Malinau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 17,"name" => "Kabupaten Nunukan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 17,"name" => "Kabupaten Tana Tidung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 17,"name" => "Kota Tarakan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Bolaang Mongondow","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Bolaang Mongondow Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Bolaang Mongondow Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Bolaang Mongondow Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Kepulauan Sangihe","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Kepulauan Siau Tagulandang Biaro","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Kepulauan Talaud","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Minahasa","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Minahasa Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Minahasa Tenggara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kabupaten Minahasa Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kota Bitung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kota Kotamobagu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kota Manado","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 18,"name" => "Kota Tomohon","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kabupaten Boalemo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kabupaten Bone Bolango","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kabupaten Gorontalo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kabupaten Gorontalo Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kabupaten Pohuwato","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 19,"name" => "Kota Gorontalo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Banggai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Banggai Kepulauan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Banggai Laut","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Buol","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Donggala","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Morowali","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Morowali Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Parigi Moutong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Poso","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Sigi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Tojo Una-Una","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kabupaten Tolitoli","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 20,"name" => "Kota Palu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Majene","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Mamasa","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Mamuju","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Mamuju Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Pasangkayu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 21,"name" => "Kabupaten Polewali Mandar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Asahan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Batu Bara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Dairi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Deli Serdang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Humbang Hasundutan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Karo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Labuhanbatu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Labuhanbatu Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Labuhanbatu Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Langkat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Mandailing Natal","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Nias","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Nias Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Nias Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Nias Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Padang Lawas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Padang Lawas Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Pakpak Bharat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Samosir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Serdang Bedagai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Simalungun","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Tapanuli Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Tapanuli Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Tapanuli Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kabupaten Toba","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Binjai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Gunungsitoli","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Medan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Padang Sidempuan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Pematangsiantar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Sibolga","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Tanjungbalai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 22,"name" => "Kota Tebing Tinggi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Bantaeng","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Barru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Bone","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Bulukumba","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Enrekang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Gowa","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Jeneponto","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Kepulauan Selayar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Luwu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Luwu Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Luwu Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Maros","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Pangkajene dan Kepulauan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Pinrang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Sidenreng Rappang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Sinjai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Soppeng","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Takalar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Tana Toraja","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Toraja Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kabupaten Wajo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kota Makassar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kota Palopo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 23,"name" => "Kota Parepare","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Bombana","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Buton","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Buton Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Buton Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Buton Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Kolaka","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Kolaka Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Kolaka Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Konawe","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Konawe Kepulauan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Konawe Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Konawe Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Muna","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Muna Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kabupaten Wakatobi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kota Baubau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 24,"name" => "Kota Kendari","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Buru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Buru Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Kepulauan Aru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Kepulauan Tanimbar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Maluku Barat Daya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Maluku Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Maluku Tenggara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Seram Bagian Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kabupaten Seram Bagian Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kota Ambon","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 25,"name" => "Kota Tual","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Halmahera Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Halmahera Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Halmahera Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Halmahera Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Halmahera Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Kepulauan Sula","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Pulau Morotai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kabupaten Pulau Taliabu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kota Ternate","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 26,"name" => "Kota Tidore Kepulauan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Biak Numfor","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Jayapura","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Keerom","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Kepulauan Yapen","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Mamberamo Raya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Sarmi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Supiori","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kabupaten Waropen","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 27,"name" => "Kota Jayapura","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Fakfak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Kaimana","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Manokwari","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Manokwari Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Pegunungan Arfak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Teluk Bintuni","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 28,"name" => "Kabupaten Teluk Wondama","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Jayawijaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Lanny Jaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Mamberamo Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Nduga","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Pegunungan Bintang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Tolikara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Yalimo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 29,"name" => "Kabupaten Yahukimo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 30,"name" => "Kabupaten Asmat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 30,"name" => "Kabupaten Boven Digoel","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 30,"name" => "Kabupaten Mappi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 30,"name" => "Kabupaten Merauke","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Deiyai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Dogiyai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Intan Jaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Mimika","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Nabire","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Paniai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Puncak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 31,"name" => "Kabupaten Puncak Jaya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kabupaten Maybrat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kabupaten Raja Ampat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kabupaten Sorong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kabupaten Sorong Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kabupaten Tambrauw","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 32,"name" => "Kota Sorong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Agam","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Dharmasraya","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Kepulauan Mentawai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Lima Puluh Kota","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Padang Pariaman","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Pasaman","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Pasaman Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Pesisir Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Sijunjung","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Solok","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Solok Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kabupaten Tanah Datar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Bukittinggi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Padang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Padang Panjang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Pariaman","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Payakumbuh","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Sawahlunto","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 33,"name" => "Kota Solok","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Bengkalis","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Indragiri Hilir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Indragiri Hulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Kampar","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Kepulauan Meranti","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Kuantan Singingi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Pelalawan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Rokan Hilir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Rokan Hulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kabupaten Siak","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kota Dumai","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 34,"name" => "Kota Pekanbaru","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kabupaten Bintan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kabupaten Karimun","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kabupaten Kepulauan Anambas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kabupaten Lingga","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kabupaten Natuna","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kota Batam","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 35,"name" => "Kota Tanjungpinang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Batanghari","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Bungo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Kerinci","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Merangin","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Muaro Jambi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Sarolangun","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Tanjung Jabung Barat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Tanjung Jabung Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kabupaten Tebo","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kota Jambi","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 36,"name" => "Kota Sungai Penuh","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Bengkulu Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Bengkulu Tengah","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Bengkulu Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Kaur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Kepahiang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Lebong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Mukomuko","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Rejang Lebong","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kabupaten Seluma","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 37,"name" => "Kota Bengkulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Banyuasin","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Empat Lawang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Lahat","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Muara Enim","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Musi Banyuasin","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Musi Rawas","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Musi Rawas Utara","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Ogan Ilir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Ogan Komering Ilir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Ogan Komering Ulu","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Ogan Komering Ulu Selatan","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Ogan Komering Ulu Timur","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kabupaten Penukal Abab Lematang Ilir","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kota Lubuklinggau","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kota Pagar Alam","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kota Palembang","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);
        DB::table("cities")->insert(["province_id" => 38,"name" => "Kota Prabumulih","created_at" => Carbon::now()->toDateTimeString(),"updated_at" => Carbon::now()->toDateTimeString()]);        
    }
}
